//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Runtime.CompilerServices;
using System.Runtime.Intrinsics;
using System.Runtime.InteropServices;
namespace DualDrill.Mathematics;
using static DMath;

[StructLayout(LayoutKind.Sequential)]
public partial struct vec4i64{
    internal Vector256<System.Int64> Data;
    
    public System.Int64 x {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => Data[0];
        
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        set {
            Data = Vector256.Create(value, Data[1], Data[2], Data[3]);
        }
        
    }
    
    public System.Int64 y {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => Data[1];
        
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        set {
            Data = Vector256.Create(Data[0], value, Data[2], Data[3]);
        }
        
    }
    
    public System.Int64 z {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => Data[2];
        
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        set {
            Data = Vector256.Create(Data[0], Data[1], value, Data[3]);
        }
        
    }
    
    public System.Int64 w {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => Data[3];
        
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        set {
            Data = Vector256.Create(Data[0], Data[1], Data[2], value);
        }
        
    }
    
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static vec4i64 operator -(vec4i64 v)
    {
        return new() { Data = - v.Data };
    }
    
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static vec4i64 operator +(vec4i64 left, vec4i64 right)
    {
        return new() { Data = left.Data + right.Data };
    }
    
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static vec4i64 operator -(vec4i64 left, vec4i64 right)
    {
        return new() { Data = left.Data - right.Data };
    }
    
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static vec4i64 operator *(vec4i64 left, vec4i64 right)
    {
        return new() { Data = left.Data * right.Data };
    }
    
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static vec4i64 operator /(vec4i64 left, vec4i64 right)
    {
        return new() { Data = left.Data / right.Data };
    }
    
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static vec4i64 operator %(vec4i64 left, vec4i64 right)
    {
        return vec4((System.Int64)(left.x % right.x), (System.Int64)(left.y % right.y), (System.Int64)(left.z % right.z), (System.Int64)(left.w % right.w));
    }
    
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static vec4i64 operator +(System.Int64 left, vec4i64 right)
    {
        return new() { Data = Vector256.Create(left) + right.Data };
    }
    
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static vec4i64 operator +(vec4i64 left, System.Int64 right)
    {
        return new() { Data = left.Data + Vector256.Create(right) };
    }
    
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static vec4i64 operator -(System.Int64 left, vec4i64 right)
    {
        return new() { Data = Vector256.Create(left) - right.Data };
    }
    
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static vec4i64 operator -(vec4i64 left, System.Int64 right)
    {
        return new() { Data = left.Data - Vector256.Create(right) };
    }
    
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static vec4i64 operator *(System.Int64 left, vec4i64 right)
    {
        return new() { Data = Vector256.Create(left) * right.Data };
    }
    
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static vec4i64 operator *(vec4i64 left, System.Int64 right)
    {
        return new() { Data = left.Data * Vector256.Create(right) };
    }
    
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static vec4i64 operator /(System.Int64 left, vec4i64 right)
    {
        return new() { Data = Vector256.Create(left) / right.Data };
    }
    
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static vec4i64 operator /(vec4i64 left, System.Int64 right)
    {
        return new() { Data = left.Data / Vector256.Create(right) };
    }
    
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static vec4i64 operator %(System.Int64 left, vec4i64 right)
    {
        return vec4((System.Int64)(left % right.x), (System.Int64)(left % right.y), (System.Int64)(left % right.z), (System.Int64)(left % right.w));
    }
    
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static vec4i64 operator %(vec4i64 left, System.Int64 right)
    {
        return vec4((System.Int64)(left.x % right), (System.Int64)(left.y % right), (System.Int64)(left.z % right), (System.Int64)(left.w % right));
    }
    
    public vec2i64 xx {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec2(x, x);
    }
    
    public vec2i64 yx {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec2(y, x);
        
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        set 
        {
            y = value.x;
            x = value.y;
        }
        
    }
    
    public vec2i64 zx {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec2(z, x);
        
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        set 
        {
            z = value.x;
            x = value.y;
        }
        
    }
    
    public vec2i64 wx {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec2(w, x);
        
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        set 
        {
            w = value.x;
            x = value.y;
        }
        
    }
    
    public vec2i64 xy {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec2(x, y);
        
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        set 
        {
            x = value.x;
            y = value.y;
        }
        
    }
    
    public vec2i64 yy {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec2(y, y);
    }
    
    public vec2i64 zy {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec2(z, y);
        
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        set 
        {
            z = value.x;
            y = value.y;
        }
        
    }
    
    public vec2i64 wy {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec2(w, y);
        
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        set 
        {
            w = value.x;
            y = value.y;
        }
        
    }
    
    public vec2i64 xz {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec2(x, z);
        
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        set 
        {
            x = value.x;
            z = value.y;
        }
        
    }
    
    public vec2i64 yz {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec2(y, z);
        
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        set 
        {
            y = value.x;
            z = value.y;
        }
        
    }
    
    public vec2i64 zz {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec2(z, z);
    }
    
    public vec2i64 wz {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec2(w, z);
        
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        set 
        {
            w = value.x;
            z = value.y;
        }
        
    }
    
    public vec2i64 xw {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec2(x, w);
        
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        set 
        {
            x = value.x;
            w = value.y;
        }
        
    }
    
    public vec2i64 yw {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec2(y, w);
        
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        set 
        {
            y = value.x;
            w = value.y;
        }
        
    }
    
    public vec2i64 zw {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec2(z, w);
        
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        set 
        {
            z = value.x;
            w = value.y;
        }
        
    }
    
    public vec2i64 ww {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec2(w, w);
    }
    
    public vec3i64 xxx {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec3(x, x, x);
    }
    
    public vec3i64 yxx {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec3(y, x, x);
    }
    
    public vec3i64 zxx {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec3(z, x, x);
    }
    
    public vec3i64 wxx {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec3(w, x, x);
    }
    
    public vec3i64 xyx {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec3(x, y, x);
    }
    
    public vec3i64 yyx {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec3(y, y, x);
    }
    
    public vec3i64 zyx {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec3(z, y, x);
        
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        set 
        {
            z = value.x;
            y = value.y;
            x = value.z;
        }
        
    }
    
    public vec3i64 wyx {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec3(w, y, x);
        
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        set 
        {
            w = value.x;
            y = value.y;
            x = value.z;
        }
        
    }
    
    public vec3i64 xzx {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec3(x, z, x);
    }
    
    public vec3i64 yzx {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec3(y, z, x);
        
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        set 
        {
            y = value.x;
            z = value.y;
            x = value.z;
        }
        
    }
    
    public vec3i64 zzx {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec3(z, z, x);
    }
    
    public vec3i64 wzx {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec3(w, z, x);
        
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        set 
        {
            w = value.x;
            z = value.y;
            x = value.z;
        }
        
    }
    
    public vec3i64 xwx {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec3(x, w, x);
    }
    
    public vec3i64 ywx {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec3(y, w, x);
        
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        set 
        {
            y = value.x;
            w = value.y;
            x = value.z;
        }
        
    }
    
    public vec3i64 zwx {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec3(z, w, x);
        
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        set 
        {
            z = value.x;
            w = value.y;
            x = value.z;
        }
        
    }
    
    public vec3i64 wwx {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec3(w, w, x);
    }
    
    public vec3i64 xxy {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec3(x, x, y);
    }
    
    public vec3i64 yxy {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec3(y, x, y);
    }
    
    public vec3i64 zxy {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec3(z, x, y);
        
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        set 
        {
            z = value.x;
            x = value.y;
            y = value.z;
        }
        
    }
    
    public vec3i64 wxy {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec3(w, x, y);
        
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        set 
        {
            w = value.x;
            x = value.y;
            y = value.z;
        }
        
    }
    
    public vec3i64 xyy {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec3(x, y, y);
    }
    
    public vec3i64 yyy {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec3(y, y, y);
    }
    
    public vec3i64 zyy {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec3(z, y, y);
    }
    
    public vec3i64 wyy {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec3(w, y, y);
    }
    
    public vec3i64 xzy {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec3(x, z, y);
        
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        set 
        {
            x = value.x;
            z = value.y;
            y = value.z;
        }
        
    }
    
    public vec3i64 yzy {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec3(y, z, y);
    }
    
    public vec3i64 zzy {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec3(z, z, y);
    }
    
    public vec3i64 wzy {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec3(w, z, y);
        
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        set 
        {
            w = value.x;
            z = value.y;
            y = value.z;
        }
        
    }
    
    public vec3i64 xwy {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec3(x, w, y);
        
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        set 
        {
            x = value.x;
            w = value.y;
            y = value.z;
        }
        
    }
    
    public vec3i64 ywy {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec3(y, w, y);
    }
    
    public vec3i64 zwy {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec3(z, w, y);
        
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        set 
        {
            z = value.x;
            w = value.y;
            y = value.z;
        }
        
    }
    
    public vec3i64 wwy {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec3(w, w, y);
    }
    
    public vec3i64 xxz {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec3(x, x, z);
    }
    
    public vec3i64 yxz {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec3(y, x, z);
        
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        set 
        {
            y = value.x;
            x = value.y;
            z = value.z;
        }
        
    }
    
    public vec3i64 zxz {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec3(z, x, z);
    }
    
    public vec3i64 wxz {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec3(w, x, z);
        
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        set 
        {
            w = value.x;
            x = value.y;
            z = value.z;
        }
        
    }
    
    public vec3i64 xyz {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec3(x, y, z);
        
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        set 
        {
            x = value.x;
            y = value.y;
            z = value.z;
        }
        
    }
    
    public vec3i64 yyz {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec3(y, y, z);
    }
    
    public vec3i64 zyz {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec3(z, y, z);
    }
    
    public vec3i64 wyz {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec3(w, y, z);
        
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        set 
        {
            w = value.x;
            y = value.y;
            z = value.z;
        }
        
    }
    
    public vec3i64 xzz {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec3(x, z, z);
    }
    
    public vec3i64 yzz {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec3(y, z, z);
    }
    
    public vec3i64 zzz {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec3(z, z, z);
    }
    
    public vec3i64 wzz {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec3(w, z, z);
    }
    
    public vec3i64 xwz {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec3(x, w, z);
        
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        set 
        {
            x = value.x;
            w = value.y;
            z = value.z;
        }
        
    }
    
    public vec3i64 ywz {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec3(y, w, z);
        
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        set 
        {
            y = value.x;
            w = value.y;
            z = value.z;
        }
        
    }
    
    public vec3i64 zwz {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec3(z, w, z);
    }
    
    public vec3i64 wwz {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec3(w, w, z);
    }
    
    public vec3i64 xxw {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec3(x, x, w);
    }
    
    public vec3i64 yxw {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec3(y, x, w);
        
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        set 
        {
            y = value.x;
            x = value.y;
            w = value.z;
        }
        
    }
    
    public vec3i64 zxw {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec3(z, x, w);
        
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        set 
        {
            z = value.x;
            x = value.y;
            w = value.z;
        }
        
    }
    
    public vec3i64 wxw {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec3(w, x, w);
    }
    
    public vec3i64 xyw {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec3(x, y, w);
        
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        set 
        {
            x = value.x;
            y = value.y;
            w = value.z;
        }
        
    }
    
    public vec3i64 yyw {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec3(y, y, w);
    }
    
    public vec3i64 zyw {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec3(z, y, w);
        
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        set 
        {
            z = value.x;
            y = value.y;
            w = value.z;
        }
        
    }
    
    public vec3i64 wyw {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec3(w, y, w);
    }
    
    public vec3i64 xzw {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec3(x, z, w);
        
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        set 
        {
            x = value.x;
            z = value.y;
            w = value.z;
        }
        
    }
    
    public vec3i64 yzw {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec3(y, z, w);
        
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        set 
        {
            y = value.x;
            z = value.y;
            w = value.z;
        }
        
    }
    
    public vec3i64 zzw {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec3(z, z, w);
    }
    
    public vec3i64 wzw {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec3(w, z, w);
    }
    
    public vec3i64 xww {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec3(x, w, w);
    }
    
    public vec3i64 yww {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec3(y, w, w);
    }
    
    public vec3i64 zww {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec3(z, w, w);
    }
    
    public vec3i64 www {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec3(w, w, w);
    }
    
    public vec4i64 xxxx {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(x, x, x, x);
    }
    
    public vec4i64 yxxx {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(y, x, x, x);
    }
    
    public vec4i64 zxxx {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(z, x, x, x);
    }
    
    public vec4i64 wxxx {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(w, x, x, x);
    }
    
    public vec4i64 xyxx {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(x, y, x, x);
    }
    
    public vec4i64 yyxx {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(y, y, x, x);
    }
    
    public vec4i64 zyxx {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(z, y, x, x);
    }
    
    public vec4i64 wyxx {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(w, y, x, x);
    }
    
    public vec4i64 xzxx {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(x, z, x, x);
    }
    
    public vec4i64 yzxx {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(y, z, x, x);
    }
    
    public vec4i64 zzxx {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(z, z, x, x);
    }
    
    public vec4i64 wzxx {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(w, z, x, x);
    }
    
    public vec4i64 xwxx {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(x, w, x, x);
    }
    
    public vec4i64 ywxx {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(y, w, x, x);
    }
    
    public vec4i64 zwxx {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(z, w, x, x);
    }
    
    public vec4i64 wwxx {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(w, w, x, x);
    }
    
    public vec4i64 xxyx {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(x, x, y, x);
    }
    
    public vec4i64 yxyx {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(y, x, y, x);
    }
    
    public vec4i64 zxyx {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(z, x, y, x);
    }
    
    public vec4i64 wxyx {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(w, x, y, x);
    }
    
    public vec4i64 xyyx {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(x, y, y, x);
    }
    
    public vec4i64 yyyx {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(y, y, y, x);
    }
    
    public vec4i64 zyyx {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(z, y, y, x);
    }
    
    public vec4i64 wyyx {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(w, y, y, x);
    }
    
    public vec4i64 xzyx {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(x, z, y, x);
    }
    
    public vec4i64 yzyx {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(y, z, y, x);
    }
    
    public vec4i64 zzyx {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(z, z, y, x);
    }
    
    public vec4i64 wzyx {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(w, z, y, x);
    }
    
    public vec4i64 xwyx {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(x, w, y, x);
    }
    
    public vec4i64 ywyx {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(y, w, y, x);
    }
    
    public vec4i64 zwyx {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(z, w, y, x);
    }
    
    public vec4i64 wwyx {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(w, w, y, x);
    }
    
    public vec4i64 xxzx {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(x, x, z, x);
    }
    
    public vec4i64 yxzx {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(y, x, z, x);
    }
    
    public vec4i64 zxzx {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(z, x, z, x);
    }
    
    public vec4i64 wxzx {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(w, x, z, x);
    }
    
    public vec4i64 xyzx {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(x, y, z, x);
    }
    
    public vec4i64 yyzx {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(y, y, z, x);
    }
    
    public vec4i64 zyzx {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(z, y, z, x);
    }
    
    public vec4i64 wyzx {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(w, y, z, x);
    }
    
    public vec4i64 xzzx {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(x, z, z, x);
    }
    
    public vec4i64 yzzx {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(y, z, z, x);
    }
    
    public vec4i64 zzzx {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(z, z, z, x);
    }
    
    public vec4i64 wzzx {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(w, z, z, x);
    }
    
    public vec4i64 xwzx {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(x, w, z, x);
    }
    
    public vec4i64 ywzx {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(y, w, z, x);
    }
    
    public vec4i64 zwzx {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(z, w, z, x);
    }
    
    public vec4i64 wwzx {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(w, w, z, x);
    }
    
    public vec4i64 xxwx {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(x, x, w, x);
    }
    
    public vec4i64 yxwx {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(y, x, w, x);
    }
    
    public vec4i64 zxwx {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(z, x, w, x);
    }
    
    public vec4i64 wxwx {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(w, x, w, x);
    }
    
    public vec4i64 xywx {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(x, y, w, x);
    }
    
    public vec4i64 yywx {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(y, y, w, x);
    }
    
    public vec4i64 zywx {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(z, y, w, x);
    }
    
    public vec4i64 wywx {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(w, y, w, x);
    }
    
    public vec4i64 xzwx {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(x, z, w, x);
    }
    
    public vec4i64 yzwx {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(y, z, w, x);
    }
    
    public vec4i64 zzwx {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(z, z, w, x);
    }
    
    public vec4i64 wzwx {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(w, z, w, x);
    }
    
    public vec4i64 xwwx {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(x, w, w, x);
    }
    
    public vec4i64 ywwx {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(y, w, w, x);
    }
    
    public vec4i64 zwwx {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(z, w, w, x);
    }
    
    public vec4i64 wwwx {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(w, w, w, x);
    }
    
    public vec4i64 xxxy {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(x, x, x, y);
    }
    
    public vec4i64 yxxy {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(y, x, x, y);
    }
    
    public vec4i64 zxxy {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(z, x, x, y);
    }
    
    public vec4i64 wxxy {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(w, x, x, y);
    }
    
    public vec4i64 xyxy {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(x, y, x, y);
    }
    
    public vec4i64 yyxy {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(y, y, x, y);
    }
    
    public vec4i64 zyxy {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(z, y, x, y);
    }
    
    public vec4i64 wyxy {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(w, y, x, y);
    }
    
    public vec4i64 xzxy {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(x, z, x, y);
    }
    
    public vec4i64 yzxy {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(y, z, x, y);
    }
    
    public vec4i64 zzxy {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(z, z, x, y);
    }
    
    public vec4i64 wzxy {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(w, z, x, y);
    }
    
    public vec4i64 xwxy {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(x, w, x, y);
    }
    
    public vec4i64 ywxy {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(y, w, x, y);
    }
    
    public vec4i64 zwxy {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(z, w, x, y);
    }
    
    public vec4i64 wwxy {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(w, w, x, y);
    }
    
    public vec4i64 xxyy {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(x, x, y, y);
    }
    
    public vec4i64 yxyy {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(y, x, y, y);
    }
    
    public vec4i64 zxyy {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(z, x, y, y);
    }
    
    public vec4i64 wxyy {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(w, x, y, y);
    }
    
    public vec4i64 xyyy {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(x, y, y, y);
    }
    
    public vec4i64 yyyy {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(y, y, y, y);
    }
    
    public vec4i64 zyyy {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(z, y, y, y);
    }
    
    public vec4i64 wyyy {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(w, y, y, y);
    }
    
    public vec4i64 xzyy {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(x, z, y, y);
    }
    
    public vec4i64 yzyy {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(y, z, y, y);
    }
    
    public vec4i64 zzyy {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(z, z, y, y);
    }
    
    public vec4i64 wzyy {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(w, z, y, y);
    }
    
    public vec4i64 xwyy {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(x, w, y, y);
    }
    
    public vec4i64 ywyy {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(y, w, y, y);
    }
    
    public vec4i64 zwyy {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(z, w, y, y);
    }
    
    public vec4i64 wwyy {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(w, w, y, y);
    }
    
    public vec4i64 xxzy {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(x, x, z, y);
    }
    
    public vec4i64 yxzy {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(y, x, z, y);
    }
    
    public vec4i64 zxzy {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(z, x, z, y);
    }
    
    public vec4i64 wxzy {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(w, x, z, y);
    }
    
    public vec4i64 xyzy {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(x, y, z, y);
    }
    
    public vec4i64 yyzy {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(y, y, z, y);
    }
    
    public vec4i64 zyzy {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(z, y, z, y);
    }
    
    public vec4i64 wyzy {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(w, y, z, y);
    }
    
    public vec4i64 xzzy {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(x, z, z, y);
    }
    
    public vec4i64 yzzy {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(y, z, z, y);
    }
    
    public vec4i64 zzzy {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(z, z, z, y);
    }
    
    public vec4i64 wzzy {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(w, z, z, y);
    }
    
    public vec4i64 xwzy {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(x, w, z, y);
    }
    
    public vec4i64 ywzy {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(y, w, z, y);
    }
    
    public vec4i64 zwzy {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(z, w, z, y);
    }
    
    public vec4i64 wwzy {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(w, w, z, y);
    }
    
    public vec4i64 xxwy {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(x, x, w, y);
    }
    
    public vec4i64 yxwy {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(y, x, w, y);
    }
    
    public vec4i64 zxwy {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(z, x, w, y);
    }
    
    public vec4i64 wxwy {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(w, x, w, y);
    }
    
    public vec4i64 xywy {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(x, y, w, y);
    }
    
    public vec4i64 yywy {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(y, y, w, y);
    }
    
    public vec4i64 zywy {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(z, y, w, y);
    }
    
    public vec4i64 wywy {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(w, y, w, y);
    }
    
    public vec4i64 xzwy {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(x, z, w, y);
    }
    
    public vec4i64 yzwy {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(y, z, w, y);
    }
    
    public vec4i64 zzwy {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(z, z, w, y);
    }
    
    public vec4i64 wzwy {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(w, z, w, y);
    }
    
    public vec4i64 xwwy {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(x, w, w, y);
    }
    
    public vec4i64 ywwy {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(y, w, w, y);
    }
    
    public vec4i64 zwwy {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(z, w, w, y);
    }
    
    public vec4i64 wwwy {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(w, w, w, y);
    }
    
    public vec4i64 xxxz {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(x, x, x, z);
    }
    
    public vec4i64 yxxz {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(y, x, x, z);
    }
    
    public vec4i64 zxxz {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(z, x, x, z);
    }
    
    public vec4i64 wxxz {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(w, x, x, z);
    }
    
    public vec4i64 xyxz {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(x, y, x, z);
    }
    
    public vec4i64 yyxz {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(y, y, x, z);
    }
    
    public vec4i64 zyxz {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(z, y, x, z);
    }
    
    public vec4i64 wyxz {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(w, y, x, z);
    }
    
    public vec4i64 xzxz {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(x, z, x, z);
    }
    
    public vec4i64 yzxz {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(y, z, x, z);
    }
    
    public vec4i64 zzxz {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(z, z, x, z);
    }
    
    public vec4i64 wzxz {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(w, z, x, z);
    }
    
    public vec4i64 xwxz {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(x, w, x, z);
    }
    
    public vec4i64 ywxz {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(y, w, x, z);
    }
    
    public vec4i64 zwxz {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(z, w, x, z);
    }
    
    public vec4i64 wwxz {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(w, w, x, z);
    }
    
    public vec4i64 xxyz {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(x, x, y, z);
    }
    
    public vec4i64 yxyz {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(y, x, y, z);
    }
    
    public vec4i64 zxyz {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(z, x, y, z);
    }
    
    public vec4i64 wxyz {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(w, x, y, z);
    }
    
    public vec4i64 xyyz {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(x, y, y, z);
    }
    
    public vec4i64 yyyz {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(y, y, y, z);
    }
    
    public vec4i64 zyyz {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(z, y, y, z);
    }
    
    public vec4i64 wyyz {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(w, y, y, z);
    }
    
    public vec4i64 xzyz {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(x, z, y, z);
    }
    
    public vec4i64 yzyz {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(y, z, y, z);
    }
    
    public vec4i64 zzyz {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(z, z, y, z);
    }
    
    public vec4i64 wzyz {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(w, z, y, z);
    }
    
    public vec4i64 xwyz {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(x, w, y, z);
    }
    
    public vec4i64 ywyz {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(y, w, y, z);
    }
    
    public vec4i64 zwyz {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(z, w, y, z);
    }
    
    public vec4i64 wwyz {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(w, w, y, z);
    }
    
    public vec4i64 xxzz {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(x, x, z, z);
    }
    
    public vec4i64 yxzz {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(y, x, z, z);
    }
    
    public vec4i64 zxzz {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(z, x, z, z);
    }
    
    public vec4i64 wxzz {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(w, x, z, z);
    }
    
    public vec4i64 xyzz {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(x, y, z, z);
    }
    
    public vec4i64 yyzz {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(y, y, z, z);
    }
    
    public vec4i64 zyzz {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(z, y, z, z);
    }
    
    public vec4i64 wyzz {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(w, y, z, z);
    }
    
    public vec4i64 xzzz {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(x, z, z, z);
    }
    
    public vec4i64 yzzz {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(y, z, z, z);
    }
    
    public vec4i64 zzzz {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(z, z, z, z);
    }
    
    public vec4i64 wzzz {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(w, z, z, z);
    }
    
    public vec4i64 xwzz {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(x, w, z, z);
    }
    
    public vec4i64 ywzz {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(y, w, z, z);
    }
    
    public vec4i64 zwzz {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(z, w, z, z);
    }
    
    public vec4i64 wwzz {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(w, w, z, z);
    }
    
    public vec4i64 xxwz {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(x, x, w, z);
    }
    
    public vec4i64 yxwz {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(y, x, w, z);
    }
    
    public vec4i64 zxwz {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(z, x, w, z);
    }
    
    public vec4i64 wxwz {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(w, x, w, z);
    }
    
    public vec4i64 xywz {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(x, y, w, z);
    }
    
    public vec4i64 yywz {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(y, y, w, z);
    }
    
    public vec4i64 zywz {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(z, y, w, z);
    }
    
    public vec4i64 wywz {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(w, y, w, z);
    }
    
    public vec4i64 xzwz {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(x, z, w, z);
    }
    
    public vec4i64 yzwz {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(y, z, w, z);
    }
    
    public vec4i64 zzwz {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(z, z, w, z);
    }
    
    public vec4i64 wzwz {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(w, z, w, z);
    }
    
    public vec4i64 xwwz {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(x, w, w, z);
    }
    
    public vec4i64 ywwz {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(y, w, w, z);
    }
    
    public vec4i64 zwwz {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(z, w, w, z);
    }
    
    public vec4i64 wwwz {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(w, w, w, z);
    }
    
    public vec4i64 xxxw {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(x, x, x, w);
    }
    
    public vec4i64 yxxw {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(y, x, x, w);
    }
    
    public vec4i64 zxxw {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(z, x, x, w);
    }
    
    public vec4i64 wxxw {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(w, x, x, w);
    }
    
    public vec4i64 xyxw {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(x, y, x, w);
    }
    
    public vec4i64 yyxw {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(y, y, x, w);
    }
    
    public vec4i64 zyxw {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(z, y, x, w);
    }
    
    public vec4i64 wyxw {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(w, y, x, w);
    }
    
    public vec4i64 xzxw {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(x, z, x, w);
    }
    
    public vec4i64 yzxw {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(y, z, x, w);
    }
    
    public vec4i64 zzxw {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(z, z, x, w);
    }
    
    public vec4i64 wzxw {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(w, z, x, w);
    }
    
    public vec4i64 xwxw {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(x, w, x, w);
    }
    
    public vec4i64 ywxw {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(y, w, x, w);
    }
    
    public vec4i64 zwxw {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(z, w, x, w);
    }
    
    public vec4i64 wwxw {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(w, w, x, w);
    }
    
    public vec4i64 xxyw {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(x, x, y, w);
    }
    
    public vec4i64 yxyw {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(y, x, y, w);
    }
    
    public vec4i64 zxyw {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(z, x, y, w);
    }
    
    public vec4i64 wxyw {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(w, x, y, w);
    }
    
    public vec4i64 xyyw {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(x, y, y, w);
    }
    
    public vec4i64 yyyw {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(y, y, y, w);
    }
    
    public vec4i64 zyyw {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(z, y, y, w);
    }
    
    public vec4i64 wyyw {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(w, y, y, w);
    }
    
    public vec4i64 xzyw {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(x, z, y, w);
    }
    
    public vec4i64 yzyw {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(y, z, y, w);
    }
    
    public vec4i64 zzyw {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(z, z, y, w);
    }
    
    public vec4i64 wzyw {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(w, z, y, w);
    }
    
    public vec4i64 xwyw {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(x, w, y, w);
    }
    
    public vec4i64 ywyw {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(y, w, y, w);
    }
    
    public vec4i64 zwyw {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(z, w, y, w);
    }
    
    public vec4i64 wwyw {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(w, w, y, w);
    }
    
    public vec4i64 xxzw {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(x, x, z, w);
    }
    
    public vec4i64 yxzw {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(y, x, z, w);
    }
    
    public vec4i64 zxzw {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(z, x, z, w);
    }
    
    public vec4i64 wxzw {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(w, x, z, w);
    }
    
    public vec4i64 xyzw {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(x, y, z, w);
    }
    
    public vec4i64 yyzw {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(y, y, z, w);
    }
    
    public vec4i64 zyzw {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(z, y, z, w);
    }
    
    public vec4i64 wyzw {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(w, y, z, w);
    }
    
    public vec4i64 xzzw {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(x, z, z, w);
    }
    
    public vec4i64 yzzw {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(y, z, z, w);
    }
    
    public vec4i64 zzzw {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(z, z, z, w);
    }
    
    public vec4i64 wzzw {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(w, z, z, w);
    }
    
    public vec4i64 xwzw {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(x, w, z, w);
    }
    
    public vec4i64 ywzw {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(y, w, z, w);
    }
    
    public vec4i64 zwzw {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(z, w, z, w);
    }
    
    public vec4i64 wwzw {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(w, w, z, w);
    }
    
    public vec4i64 xxww {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(x, x, w, w);
    }
    
    public vec4i64 yxww {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(y, x, w, w);
    }
    
    public vec4i64 zxww {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(z, x, w, w);
    }
    
    public vec4i64 wxww {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(w, x, w, w);
    }
    
    public vec4i64 xyww {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(x, y, w, w);
    }
    
    public vec4i64 yyww {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(y, y, w, w);
    }
    
    public vec4i64 zyww {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(z, y, w, w);
    }
    
    public vec4i64 wyww {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(w, y, w, w);
    }
    
    public vec4i64 xzww {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(x, z, w, w);
    }
    
    public vec4i64 yzww {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(y, z, w, w);
    }
    
    public vec4i64 zzww {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(z, z, w, w);
    }
    
    public vec4i64 wzww {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(w, z, w, w);
    }
    
    public vec4i64 xwww {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(x, w, w, w);
    }
    
    public vec4i64 ywww {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(y, w, w, w);
    }
    
    public vec4i64 zwww {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(z, w, w, w);
    }
    
    public vec4i64 wwww {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => vec4(w, w, w, w);
    }
    
}

public static partial class DMath{
    public static vec4i64 vec4(System.Int64 x, System.Int64 y, System.Int64 z, System.Int64 w){
        return new vec4i64() { Data = Vector256.Create(x, y, z, w) };
    }
    
    public static vec4i64 vec4(System.Int64 e) => vec4(e, e, e, e);
    public static vec4i64 vec4(System.Int64 e0, vec3i64 e1) => vec4(e0, e1.x, e1.y, e1.z);
    public static vec4i64 vec4(vec3i64 e0, System.Int64 e1) => vec4(e0.x, e0.y, e0.z, e1);
    public static vec4i64 vec4(System.Int64 e0, System.Int64 e1, vec2i64 e2) => vec4(e0, e1, e2.x, e2.y);
    public static vec4i64 vec4(System.Int64 e0, vec2i64 e1, System.Int64 e2) => vec4(e0, e1.x, e1.y, e2);
    public static vec4i64 vec4(vec2i64 e0, System.Int64 e1, System.Int64 e2) => vec4(e0.x, e0.y, e1, e2);
    public static vec4i64 vec4(vec2i64 e0, vec2i64 e1) => vec4(e0.x, e0.y, e1.x, e1.y);
}

