//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DualDrill.Mathematics
{


    [System.Runtime.InteropServices.StructLayoutAttribute(System.Runtime.InteropServices.LayoutKind.Sequential)]
    public partial struct vec2b
    {

        public bool x;

        public bool y;
    }

    [System.Runtime.InteropServices.StructLayoutAttribute(System.Runtime.InteropServices.LayoutKind.Sequential)]
    public partial struct vec2i8
    {

        public sbyte x;

        public sbyte y;
    }

    [System.Runtime.InteropServices.StructLayoutAttribute(System.Runtime.InteropServices.LayoutKind.Sequential)]
    public partial struct vec2i16
    {

        public short x;

        public short y;
    }

    [System.Runtime.InteropServices.StructLayoutAttribute(System.Runtime.InteropServices.LayoutKind.Sequential)]
    public partial struct vec2i32
    {

        public int x;

        public int y;
    }

    [System.Runtime.InteropServices.StructLayoutAttribute(System.Runtime.InteropServices.LayoutKind.Sequential)]
    public partial struct vec2i64
    {

        public long x;

        public long y;
    }

    [System.Runtime.InteropServices.StructLayoutAttribute(System.Runtime.InteropServices.LayoutKind.Sequential)]
    public partial struct vec2u8
    {

        public byte x;

        public byte y;
    }

    [System.Runtime.InteropServices.StructLayoutAttribute(System.Runtime.InteropServices.LayoutKind.Sequential)]
    public partial struct vec2u16
    {

        public ushort x;

        public ushort y;
    }

    [System.Runtime.InteropServices.StructLayoutAttribute(System.Runtime.InteropServices.LayoutKind.Sequential)]
    public partial struct vec2u32
    {

        public uint x;

        public uint y;
    }

    [System.Runtime.InteropServices.StructLayoutAttribute(System.Runtime.InteropServices.LayoutKind.Sequential)]
    public partial struct vec2u64
    {

        public ulong x;

        public ulong y;
    }

    [System.Runtime.InteropServices.StructLayoutAttribute(System.Runtime.InteropServices.LayoutKind.Sequential)]
    public partial struct vec2f16
    {

        public System.Half x;

        public System.Half y;
    }

    [System.Runtime.InteropServices.StructLayoutAttribute(System.Runtime.InteropServices.LayoutKind.Sequential)]
    public partial struct vec2f32
    {

        public float x;

        public float y;
    }

    [System.Runtime.InteropServices.StructLayoutAttribute(System.Runtime.InteropServices.LayoutKind.Sequential)]
    public partial struct vec2f64
    {

        public double x;

        public double y;
    }

    [System.Runtime.InteropServices.StructLayoutAttribute(System.Runtime.InteropServices.LayoutKind.Sequential)]
    public partial struct vec3b
    {

        public bool x;

        public bool y;

        public bool z;
    }

    [System.Runtime.InteropServices.StructLayoutAttribute(System.Runtime.InteropServices.LayoutKind.Sequential)]
    public partial struct vec3i8
    {

        public sbyte x;

        public sbyte y;

        public sbyte z;
    }

    [System.Runtime.InteropServices.StructLayoutAttribute(System.Runtime.InteropServices.LayoutKind.Sequential)]
    public partial struct vec3i16
    {

        public short x;

        public short y;

        public short z;
    }

    [System.Runtime.InteropServices.StructLayoutAttribute(System.Runtime.InteropServices.LayoutKind.Sequential)]
    public partial struct vec3i32
    {

        public int x;

        public int y;

        public int z;
    }

    [System.Runtime.InteropServices.StructLayoutAttribute(System.Runtime.InteropServices.LayoutKind.Sequential)]
    public partial struct vec3i64
    {

        public long x;

        public long y;

        public long z;
    }

    [System.Runtime.InteropServices.StructLayoutAttribute(System.Runtime.InteropServices.LayoutKind.Sequential)]
    public partial struct vec3u8
    {

        public byte x;

        public byte y;

        public byte z;
    }

    [System.Runtime.InteropServices.StructLayoutAttribute(System.Runtime.InteropServices.LayoutKind.Sequential)]
    public partial struct vec3u16
    {

        public ushort x;

        public ushort y;

        public ushort z;
    }

    [System.Runtime.InteropServices.StructLayoutAttribute(System.Runtime.InteropServices.LayoutKind.Sequential)]
    public partial struct vec3u32
    {

        public uint x;

        public uint y;

        public uint z;
    }

    [System.Runtime.InteropServices.StructLayoutAttribute(System.Runtime.InteropServices.LayoutKind.Sequential)]
    public partial struct vec3u64
    {

        public ulong x;

        public ulong y;

        public ulong z;
    }

    [System.Runtime.InteropServices.StructLayoutAttribute(System.Runtime.InteropServices.LayoutKind.Sequential)]
    public partial struct vec3f16
    {

        public System.Half x;

        public System.Half y;

        public System.Half z;
    }

    [System.Runtime.InteropServices.StructLayoutAttribute(System.Runtime.InteropServices.LayoutKind.Sequential)]
    public partial struct vec3f32
    {

        public float x;

        public float y;

        public float z;
    }

    [System.Runtime.InteropServices.StructLayoutAttribute(System.Runtime.InteropServices.LayoutKind.Sequential)]
    public partial struct vec3f64
    {

        public double x;

        public double y;

        public double z;
    }

    [System.Runtime.InteropServices.StructLayoutAttribute(System.Runtime.InteropServices.LayoutKind.Sequential)]
    public partial struct vec4b
    {

        public bool x;

        public bool y;

        public bool z;

        public bool w;
    }

    [System.Runtime.InteropServices.StructLayoutAttribute(System.Runtime.InteropServices.LayoutKind.Sequential)]
    public partial struct vec4i8
    {

        public sbyte x;

        public sbyte y;

        public sbyte z;

        public sbyte w;
    }

    [System.Runtime.InteropServices.StructLayoutAttribute(System.Runtime.InteropServices.LayoutKind.Sequential)]
    public partial struct vec4i16
    {

        public short x;

        public short y;

        public short z;

        public short w;
    }

    [System.Runtime.InteropServices.StructLayoutAttribute(System.Runtime.InteropServices.LayoutKind.Sequential)]
    public partial struct vec4i32
    {

        public int x;

        public int y;

        public int z;

        public int w;
    }

    [System.Runtime.InteropServices.StructLayoutAttribute(System.Runtime.InteropServices.LayoutKind.Sequential)]
    public partial struct vec4i64
    {

        public long x;

        public long y;

        public long z;

        public long w;
    }

    [System.Runtime.InteropServices.StructLayoutAttribute(System.Runtime.InteropServices.LayoutKind.Sequential)]
    public partial struct vec4u8
    {

        public byte x;

        public byte y;

        public byte z;

        public byte w;
    }

    [System.Runtime.InteropServices.StructLayoutAttribute(System.Runtime.InteropServices.LayoutKind.Sequential)]
    public partial struct vec4u16
    {

        public ushort x;

        public ushort y;

        public ushort z;

        public ushort w;
    }

    [System.Runtime.InteropServices.StructLayoutAttribute(System.Runtime.InteropServices.LayoutKind.Sequential)]
    public partial struct vec4u32
    {

        public uint x;

        public uint y;

        public uint z;

        public uint w;
    }

    [System.Runtime.InteropServices.StructLayoutAttribute(System.Runtime.InteropServices.LayoutKind.Sequential)]
    public partial struct vec4u64
    {

        public ulong x;

        public ulong y;

        public ulong z;

        public ulong w;
    }

    [System.Runtime.InteropServices.StructLayoutAttribute(System.Runtime.InteropServices.LayoutKind.Sequential)]
    public partial struct vec4f16
    {

        public System.Half x;

        public System.Half y;

        public System.Half z;

        public System.Half w;
    }

    [System.Runtime.InteropServices.StructLayoutAttribute(System.Runtime.InteropServices.LayoutKind.Sequential)]
    public partial struct vec4f32
    {

        public float x;

        public float y;

        public float z;

        public float w;
    }

    [System.Runtime.InteropServices.StructLayoutAttribute(System.Runtime.InteropServices.LayoutKind.Sequential)]
    public partial struct vec4f64
    {

        public double x;

        public double y;

        public double z;

        public double w;
    }

    public partial class DMath
    {

        [System.Runtime.CompilerServices.MethodImplAttribute(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        public static vec2b vec2(bool x, bool y)
        {
            vec2b result = new vec2b();
            result.x = x;
            result.y = y;
            return result;
        }

        [System.Runtime.CompilerServices.MethodImplAttribute(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        public static vec2b vec2(bool e)
        {
            return DMath.vec2(e, e);
        }

        [System.Runtime.CompilerServices.MethodImplAttribute(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        public static vec2i8 vec2(sbyte x, sbyte y)
        {
            vec2i8 result = new vec2i8();
            result.x = x;
            result.y = y;
            return result;
        }

        [System.Runtime.CompilerServices.MethodImplAttribute(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        public static vec2i8 vec2(sbyte e)
        {
            return DMath.vec2(e, e);
        }

        [System.Runtime.CompilerServices.MethodImplAttribute(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        public static vec2i16 vec2(short x, short y)
        {
            vec2i16 result = new vec2i16();
            result.x = x;
            result.y = y;
            return result;
        }

        [System.Runtime.CompilerServices.MethodImplAttribute(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        public static vec2i16 vec2(short e)
        {
            return DMath.vec2(e, e);
        }

        [System.Runtime.CompilerServices.MethodImplAttribute(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        public static vec2i32 vec2(int x, int y)
        {
            vec2i32 result = new vec2i32();
            result.x = x;
            result.y = y;
            return result;
        }

        [System.Runtime.CompilerServices.MethodImplAttribute(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        public static vec2i32 vec2(int e)
        {
            return DMath.vec2(e, e);
        }

        [System.Runtime.CompilerServices.MethodImplAttribute(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        public static vec2i64 vec2(long x, long y)
        {
            vec2i64 result = new vec2i64();
            result.x = x;
            result.y = y;
            return result;
        }

        [System.Runtime.CompilerServices.MethodImplAttribute(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        public static vec2i64 vec2(long e)
        {
            return DMath.vec2(e, e);
        }

        [System.Runtime.CompilerServices.MethodImplAttribute(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        public static vec2u8 vec2(byte x, byte y)
        {
            vec2u8 result = new vec2u8();
            result.x = x;
            result.y = y;
            return result;
        }

        [System.Runtime.CompilerServices.MethodImplAttribute(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        public static vec2u8 vec2(byte e)
        {
            return DMath.vec2(e, e);
        }

        [System.Runtime.CompilerServices.MethodImplAttribute(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        public static vec2u16 vec2(ushort x, ushort y)
        {
            vec2u16 result = new vec2u16();
            result.x = x;
            result.y = y;
            return result;
        }

        [System.Runtime.CompilerServices.MethodImplAttribute(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        public static vec2u16 vec2(ushort e)
        {
            return DMath.vec2(e, e);
        }

        [System.Runtime.CompilerServices.MethodImplAttribute(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        public static vec2u32 vec2(uint x, uint y)
        {
            vec2u32 result = new vec2u32();
            result.x = x;
            result.y = y;
            return result;
        }

        [System.Runtime.CompilerServices.MethodImplAttribute(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        public static vec2u32 vec2(uint e)
        {
            return DMath.vec2(e, e);
        }

        [System.Runtime.CompilerServices.MethodImplAttribute(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        public static vec2u64 vec2(ulong x, ulong y)
        {
            vec2u64 result = new vec2u64();
            result.x = x;
            result.y = y;
            return result;
        }

        [System.Runtime.CompilerServices.MethodImplAttribute(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        public static vec2u64 vec2(ulong e)
        {
            return DMath.vec2(e, e);
        }

        [System.Runtime.CompilerServices.MethodImplAttribute(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        public static vec2f16 vec2(System.Half x, System.Half y)
        {
            vec2f16 result = new vec2f16();
            result.x = x;
            result.y = y;
            return result;
        }

        [System.Runtime.CompilerServices.MethodImplAttribute(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        public static vec2f16 vec2(System.Half e)
        {
            return DMath.vec2(e, e);
        }

        [System.Runtime.CompilerServices.MethodImplAttribute(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        public static vec2f32 vec2(float x, float y)
        {
            vec2f32 result = new vec2f32();
            result.x = x;
            result.y = y;
            return result;
        }

        [System.Runtime.CompilerServices.MethodImplAttribute(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        public static vec2f32 vec2(float e)
        {
            return DMath.vec2(e, e);
        }

        [System.Runtime.CompilerServices.MethodImplAttribute(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        public static vec2f64 vec2(double x, double y)
        {
            vec2f64 result = new vec2f64();
            result.x = x;
            result.y = y;
            return result;
        }

        [System.Runtime.CompilerServices.MethodImplAttribute(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        public static vec2f64 vec2(double e)
        {
            return DMath.vec2(e, e);
        }

        [System.Runtime.CompilerServices.MethodImplAttribute(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        public static vec3b vec3(bool x, bool y, bool z)
        {
            vec3b result = new vec3b();
            result.x = x;
            result.y = y;
            result.z = z;
            return result;
        }

        [System.Runtime.CompilerServices.MethodImplAttribute(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        public static vec3b vec3(bool e)
        {
            return DMath.vec3(e, e, e);
        }

        [System.Runtime.CompilerServices.MethodImplAttribute(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        public static vec3b vec3(bool e0, vec2b e1)
        {
            return DMath.vec3(e0, e1.x, e1.y);
        }

        [System.Runtime.CompilerServices.MethodImplAttribute(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        public static vec3b vec3(vec2b e0, bool e1)
        {
            return DMath.vec3(e0.x, e0.y, e1);
        }

        [System.Runtime.CompilerServices.MethodImplAttribute(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        public static vec3i8 vec3(sbyte x, sbyte y, sbyte z)
        {
            vec3i8 result = new vec3i8();
            result.x = x;
            result.y = y;
            result.z = z;
            return result;
        }

        [System.Runtime.CompilerServices.MethodImplAttribute(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        public static vec3i8 vec3(sbyte e)
        {
            return DMath.vec3(e, e, e);
        }

        [System.Runtime.CompilerServices.MethodImplAttribute(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        public static vec3i8 vec3(sbyte e0, vec2i8 e1)
        {
            return DMath.vec3(e0, e1.x, e1.y);
        }

        [System.Runtime.CompilerServices.MethodImplAttribute(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        public static vec3i8 vec3(vec2i8 e0, sbyte e1)
        {
            return DMath.vec3(e0.x, e0.y, e1);
        }

        [System.Runtime.CompilerServices.MethodImplAttribute(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        public static vec3i16 vec3(short x, short y, short z)
        {
            vec3i16 result = new vec3i16();
            result.x = x;
            result.y = y;
            result.z = z;
            return result;
        }

        [System.Runtime.CompilerServices.MethodImplAttribute(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        public static vec3i16 vec3(short e)
        {
            return DMath.vec3(e, e, e);
        }

        [System.Runtime.CompilerServices.MethodImplAttribute(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        public static vec3i16 vec3(short e0, vec2i16 e1)
        {
            return DMath.vec3(e0, e1.x, e1.y);
        }

        [System.Runtime.CompilerServices.MethodImplAttribute(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        public static vec3i16 vec3(vec2i16 e0, short e1)
        {
            return DMath.vec3(e0.x, e0.y, e1);
        }

        [System.Runtime.CompilerServices.MethodImplAttribute(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        public static vec3i32 vec3(int x, int y, int z)
        {
            vec3i32 result = new vec3i32();
            result.x = x;
            result.y = y;
            result.z = z;
            return result;
        }

        [System.Runtime.CompilerServices.MethodImplAttribute(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        public static vec3i32 vec3(int e)
        {
            return DMath.vec3(e, e, e);
        }

        [System.Runtime.CompilerServices.MethodImplAttribute(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        public static vec3i32 vec3(int e0, vec2i32 e1)
        {
            return DMath.vec3(e0, e1.x, e1.y);
        }

        [System.Runtime.CompilerServices.MethodImplAttribute(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        public static vec3i32 vec3(vec2i32 e0, int e1)
        {
            return DMath.vec3(e0.x, e0.y, e1);
        }

        [System.Runtime.CompilerServices.MethodImplAttribute(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        public static vec3i64 vec3(long x, long y, long z)
        {
            vec3i64 result = new vec3i64();
            result.x = x;
            result.y = y;
            result.z = z;
            return result;
        }

        [System.Runtime.CompilerServices.MethodImplAttribute(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        public static vec3i64 vec3(long e)
        {
            return DMath.vec3(e, e, e);
        }

        [System.Runtime.CompilerServices.MethodImplAttribute(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        public static vec3i64 vec3(long e0, vec2i64 e1)
        {
            return DMath.vec3(e0, e1.x, e1.y);
        }

        [System.Runtime.CompilerServices.MethodImplAttribute(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        public static vec3i64 vec3(vec2i64 e0, long e1)
        {
            return DMath.vec3(e0.x, e0.y, e1);
        }

        [System.Runtime.CompilerServices.MethodImplAttribute(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        public static vec3u8 vec3(byte x, byte y, byte z)
        {
            vec3u8 result = new vec3u8();
            result.x = x;
            result.y = y;
            result.z = z;
            return result;
        }

        [System.Runtime.CompilerServices.MethodImplAttribute(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        public static vec3u8 vec3(byte e)
        {
            return DMath.vec3(e, e, e);
        }

        [System.Runtime.CompilerServices.MethodImplAttribute(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        public static vec3u8 vec3(byte e0, vec2u8 e1)
        {
            return DMath.vec3(e0, e1.x, e1.y);
        }

        [System.Runtime.CompilerServices.MethodImplAttribute(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        public static vec3u8 vec3(vec2u8 e0, byte e1)
        {
            return DMath.vec3(e0.x, e0.y, e1);
        }

        [System.Runtime.CompilerServices.MethodImplAttribute(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        public static vec3u16 vec3(ushort x, ushort y, ushort z)
        {
            vec3u16 result = new vec3u16();
            result.x = x;
            result.y = y;
            result.z = z;
            return result;
        }

        [System.Runtime.CompilerServices.MethodImplAttribute(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        public static vec3u16 vec3(ushort e)
        {
            return DMath.vec3(e, e, e);
        }

        [System.Runtime.CompilerServices.MethodImplAttribute(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        public static vec3u16 vec3(ushort e0, vec2u16 e1)
        {
            return DMath.vec3(e0, e1.x, e1.y);
        }

        [System.Runtime.CompilerServices.MethodImplAttribute(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        public static vec3u16 vec3(vec2u16 e0, ushort e1)
        {
            return DMath.vec3(e0.x, e0.y, e1);
        }

        [System.Runtime.CompilerServices.MethodImplAttribute(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        public static vec3u32 vec3(uint x, uint y, uint z)
        {
            vec3u32 result = new vec3u32();
            result.x = x;
            result.y = y;
            result.z = z;
            return result;
        }

        [System.Runtime.CompilerServices.MethodImplAttribute(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        public static vec3u32 vec3(uint e)
        {
            return DMath.vec3(e, e, e);
        }

        [System.Runtime.CompilerServices.MethodImplAttribute(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        public static vec3u32 vec3(uint e0, vec2u32 e1)
        {
            return DMath.vec3(e0, e1.x, e1.y);
        }

        [System.Runtime.CompilerServices.MethodImplAttribute(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        public static vec3u32 vec3(vec2u32 e0, uint e1)
        {
            return DMath.vec3(e0.x, e0.y, e1);
        }

        [System.Runtime.CompilerServices.MethodImplAttribute(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        public static vec3u64 vec3(ulong x, ulong y, ulong z)
        {
            vec3u64 result = new vec3u64();
            result.x = x;
            result.y = y;
            result.z = z;
            return result;
        }

        [System.Runtime.CompilerServices.MethodImplAttribute(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        public static vec3u64 vec3(ulong e)
        {
            return DMath.vec3(e, e, e);
        }

        [System.Runtime.CompilerServices.MethodImplAttribute(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        public static vec3u64 vec3(ulong e0, vec2u64 e1)
        {
            return DMath.vec3(e0, e1.x, e1.y);
        }

        [System.Runtime.CompilerServices.MethodImplAttribute(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        public static vec3u64 vec3(vec2u64 e0, ulong e1)
        {
            return DMath.vec3(e0.x, e0.y, e1);
        }

        [System.Runtime.CompilerServices.MethodImplAttribute(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        public static vec3f16 vec3(System.Half x, System.Half y, System.Half z)
        {
            vec3f16 result = new vec3f16();
            result.x = x;
            result.y = y;
            result.z = z;
            return result;
        }

        [System.Runtime.CompilerServices.MethodImplAttribute(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        public static vec3f16 vec3(System.Half e)
        {
            return DMath.vec3(e, e, e);
        }

        [System.Runtime.CompilerServices.MethodImplAttribute(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        public static vec3f16 vec3(System.Half e0, vec2f16 e1)
        {
            return DMath.vec3(e0, e1.x, e1.y);
        }

        [System.Runtime.CompilerServices.MethodImplAttribute(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        public static vec3f16 vec3(vec2f16 e0, System.Half e1)
        {
            return DMath.vec3(e0.x, e0.y, e1);
        }

        [System.Runtime.CompilerServices.MethodImplAttribute(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        public static vec3f32 vec3(float x, float y, float z)
        {
            vec3f32 result = new vec3f32();
            result.x = x;
            result.y = y;
            result.z = z;
            return result;
        }

        [System.Runtime.CompilerServices.MethodImplAttribute(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        public static vec3f32 vec3(float e)
        {
            return DMath.vec3(e, e, e);
        }

        [System.Runtime.CompilerServices.MethodImplAttribute(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        public static vec3f32 vec3(float e0, vec2f32 e1)
        {
            return DMath.vec3(e0, e1.x, e1.y);
        }

        [System.Runtime.CompilerServices.MethodImplAttribute(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        public static vec3f32 vec3(vec2f32 e0, float e1)
        {
            return DMath.vec3(e0.x, e0.y, e1);
        }

        [System.Runtime.CompilerServices.MethodImplAttribute(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        public static vec3f64 vec3(double x, double y, double z)
        {
            vec3f64 result = new vec3f64();
            result.x = x;
            result.y = y;
            result.z = z;
            return result;
        }

        [System.Runtime.CompilerServices.MethodImplAttribute(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        public static vec3f64 vec3(double e)
        {
            return DMath.vec3(e, e, e);
        }

        [System.Runtime.CompilerServices.MethodImplAttribute(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        public static vec3f64 vec3(double e0, vec2f64 e1)
        {
            return DMath.vec3(e0, e1.x, e1.y);
        }

        [System.Runtime.CompilerServices.MethodImplAttribute(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        public static vec3f64 vec3(vec2f64 e0, double e1)
        {
            return DMath.vec3(e0.x, e0.y, e1);
        }

        [System.Runtime.CompilerServices.MethodImplAttribute(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        public static vec4b vec4(bool x, bool y, bool z, bool w)
        {
            vec4b result = new vec4b();
            result.x = x;
            result.y = y;
            result.z = z;
            result.w = w;
            return result;
        }

        [System.Runtime.CompilerServices.MethodImplAttribute(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        public static vec4b vec4(bool e)
        {
            return DMath.vec4(e, e, e, e);
        }

        [System.Runtime.CompilerServices.MethodImplAttribute(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        public static vec4b vec4(vec2b e0, bool e1, bool e2)
        {
            return DMath.vec4(e0.x, e0.y, e1, e2);
        }

        [System.Runtime.CompilerServices.MethodImplAttribute(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        public static vec4b vec4(bool e0, vec2b e1, bool e2)
        {
            return DMath.vec4(e0, e1.x, e1.y, e2);
        }

        [System.Runtime.CompilerServices.MethodImplAttribute(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        public static vec4b vec4(bool e0, bool e1, vec2b e2)
        {
            return DMath.vec4(e0, e1, e2.x, e2.y);
        }

        [System.Runtime.CompilerServices.MethodImplAttribute(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        public static vec4b vec4(vec2b e0, vec2b e1)
        {
            return DMath.vec4(e0.x, e0.y, e1.x, e1.y);
        }

        [System.Runtime.CompilerServices.MethodImplAttribute(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        public static vec4b vec4(bool e0, vec3b e1)
        {
            return DMath.vec4(e0, e1.x, e1.y, e1.z);
        }

        [System.Runtime.CompilerServices.MethodImplAttribute(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        public static vec4b vec4(vec3b e0, bool e1)
        {
            return DMath.vec4(e0.x, e0.y, e0.z, e1);
        }

        [System.Runtime.CompilerServices.MethodImplAttribute(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        public static vec4i8 vec4(sbyte x, sbyte y, sbyte z, sbyte w)
        {
            vec4i8 result = new vec4i8();
            result.x = x;
            result.y = y;
            result.z = z;
            result.w = w;
            return result;
        }

        [System.Runtime.CompilerServices.MethodImplAttribute(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        public static vec4i8 vec4(sbyte e)
        {
            return DMath.vec4(e, e, e, e);
        }

        [System.Runtime.CompilerServices.MethodImplAttribute(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        public static vec4i8 vec4(vec2i8 e0, sbyte e1, sbyte e2)
        {
            return DMath.vec4(e0.x, e0.y, e1, e2);
        }

        [System.Runtime.CompilerServices.MethodImplAttribute(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        public static vec4i8 vec4(sbyte e0, vec2i8 e1, sbyte e2)
        {
            return DMath.vec4(e0, e1.x, e1.y, e2);
        }

        [System.Runtime.CompilerServices.MethodImplAttribute(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        public static vec4i8 vec4(sbyte e0, sbyte e1, vec2i8 e2)
        {
            return DMath.vec4(e0, e1, e2.x, e2.y);
        }

        [System.Runtime.CompilerServices.MethodImplAttribute(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        public static vec4i8 vec4(vec2i8 e0, vec2i8 e1)
        {
            return DMath.vec4(e0.x, e0.y, e1.x, e1.y);
        }

        [System.Runtime.CompilerServices.MethodImplAttribute(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        public static vec4i8 vec4(sbyte e0, vec3i8 e1)
        {
            return DMath.vec4(e0, e1.x, e1.y, e1.z);
        }

        [System.Runtime.CompilerServices.MethodImplAttribute(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        public static vec4i8 vec4(vec3i8 e0, sbyte e1)
        {
            return DMath.vec4(e0.x, e0.y, e0.z, e1);
        }

        [System.Runtime.CompilerServices.MethodImplAttribute(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        public static vec4i16 vec4(short x, short y, short z, short w)
        {
            vec4i16 result = new vec4i16();
            result.x = x;
            result.y = y;
            result.z = z;
            result.w = w;
            return result;
        }

        [System.Runtime.CompilerServices.MethodImplAttribute(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        public static vec4i16 vec4(short e)
        {
            return DMath.vec4(e, e, e, e);
        }

        [System.Runtime.CompilerServices.MethodImplAttribute(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        public static vec4i16 vec4(vec2i16 e0, short e1, short e2)
        {
            return DMath.vec4(e0.x, e0.y, e1, e2);
        }

        [System.Runtime.CompilerServices.MethodImplAttribute(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        public static vec4i16 vec4(short e0, vec2i16 e1, short e2)
        {
            return DMath.vec4(e0, e1.x, e1.y, e2);
        }

        [System.Runtime.CompilerServices.MethodImplAttribute(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        public static vec4i16 vec4(short e0, short e1, vec2i16 e2)
        {
            return DMath.vec4(e0, e1, e2.x, e2.y);
        }

        [System.Runtime.CompilerServices.MethodImplAttribute(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        public static vec4i16 vec4(vec2i16 e0, vec2i16 e1)
        {
            return DMath.vec4(e0.x, e0.y, e1.x, e1.y);
        }

        [System.Runtime.CompilerServices.MethodImplAttribute(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        public static vec4i16 vec4(short e0, vec3i16 e1)
        {
            return DMath.vec4(e0, e1.x, e1.y, e1.z);
        }

        [System.Runtime.CompilerServices.MethodImplAttribute(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        public static vec4i16 vec4(vec3i16 e0, short e1)
        {
            return DMath.vec4(e0.x, e0.y, e0.z, e1);
        }

        [System.Runtime.CompilerServices.MethodImplAttribute(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        public static vec4i32 vec4(int x, int y, int z, int w)
        {
            vec4i32 result = new vec4i32();
            result.x = x;
            result.y = y;
            result.z = z;
            result.w = w;
            return result;
        }

        [System.Runtime.CompilerServices.MethodImplAttribute(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        public static vec4i32 vec4(int e)
        {
            return DMath.vec4(e, e, e, e);
        }

        [System.Runtime.CompilerServices.MethodImplAttribute(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        public static vec4i32 vec4(vec2i32 e0, int e1, int e2)
        {
            return DMath.vec4(e0.x, e0.y, e1, e2);
        }

        [System.Runtime.CompilerServices.MethodImplAttribute(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        public static vec4i32 vec4(int e0, vec2i32 e1, int e2)
        {
            return DMath.vec4(e0, e1.x, e1.y, e2);
        }

        [System.Runtime.CompilerServices.MethodImplAttribute(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        public static vec4i32 vec4(int e0, int e1, vec2i32 e2)
        {
            return DMath.vec4(e0, e1, e2.x, e2.y);
        }

        [System.Runtime.CompilerServices.MethodImplAttribute(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        public static vec4i32 vec4(vec2i32 e0, vec2i32 e1)
        {
            return DMath.vec4(e0.x, e0.y, e1.x, e1.y);
        }

        [System.Runtime.CompilerServices.MethodImplAttribute(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        public static vec4i32 vec4(int e0, vec3i32 e1)
        {
            return DMath.vec4(e0, e1.x, e1.y, e1.z);
        }

        [System.Runtime.CompilerServices.MethodImplAttribute(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        public static vec4i32 vec4(vec3i32 e0, int e1)
        {
            return DMath.vec4(e0.x, e0.y, e0.z, e1);
        }

        [System.Runtime.CompilerServices.MethodImplAttribute(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        public static vec4i64 vec4(long x, long y, long z, long w)
        {
            vec4i64 result = new vec4i64();
            result.x = x;
            result.y = y;
            result.z = z;
            result.w = w;
            return result;
        }

        [System.Runtime.CompilerServices.MethodImplAttribute(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        public static vec4i64 vec4(long e)
        {
            return DMath.vec4(e, e, e, e);
        }

        [System.Runtime.CompilerServices.MethodImplAttribute(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        public static vec4i64 vec4(vec2i64 e0, long e1, long e2)
        {
            return DMath.vec4(e0.x, e0.y, e1, e2);
        }

        [System.Runtime.CompilerServices.MethodImplAttribute(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        public static vec4i64 vec4(long e0, vec2i64 e1, long e2)
        {
            return DMath.vec4(e0, e1.x, e1.y, e2);
        }

        [System.Runtime.CompilerServices.MethodImplAttribute(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        public static vec4i64 vec4(long e0, long e1, vec2i64 e2)
        {
            return DMath.vec4(e0, e1, e2.x, e2.y);
        }

        [System.Runtime.CompilerServices.MethodImplAttribute(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        public static vec4i64 vec4(vec2i64 e0, vec2i64 e1)
        {
            return DMath.vec4(e0.x, e0.y, e1.x, e1.y);
        }

        [System.Runtime.CompilerServices.MethodImplAttribute(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        public static vec4i64 vec4(long e0, vec3i64 e1)
        {
            return DMath.vec4(e0, e1.x, e1.y, e1.z);
        }

        [System.Runtime.CompilerServices.MethodImplAttribute(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        public static vec4i64 vec4(vec3i64 e0, long e1)
        {
            return DMath.vec4(e0.x, e0.y, e0.z, e1);
        }

        [System.Runtime.CompilerServices.MethodImplAttribute(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        public static vec4u8 vec4(byte x, byte y, byte z, byte w)
        {
            vec4u8 result = new vec4u8();
            result.x = x;
            result.y = y;
            result.z = z;
            result.w = w;
            return result;
        }

        [System.Runtime.CompilerServices.MethodImplAttribute(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        public static vec4u8 vec4(byte e)
        {
            return DMath.vec4(e, e, e, e);
        }

        [System.Runtime.CompilerServices.MethodImplAttribute(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        public static vec4u8 vec4(vec2u8 e0, byte e1, byte e2)
        {
            return DMath.vec4(e0.x, e0.y, e1, e2);
        }

        [System.Runtime.CompilerServices.MethodImplAttribute(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        public static vec4u8 vec4(byte e0, vec2u8 e1, byte e2)
        {
            return DMath.vec4(e0, e1.x, e1.y, e2);
        }

        [System.Runtime.CompilerServices.MethodImplAttribute(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        public static vec4u8 vec4(byte e0, byte e1, vec2u8 e2)
        {
            return DMath.vec4(e0, e1, e2.x, e2.y);
        }

        [System.Runtime.CompilerServices.MethodImplAttribute(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        public static vec4u8 vec4(vec2u8 e0, vec2u8 e1)
        {
            return DMath.vec4(e0.x, e0.y, e1.x, e1.y);
        }

        [System.Runtime.CompilerServices.MethodImplAttribute(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        public static vec4u8 vec4(byte e0, vec3u8 e1)
        {
            return DMath.vec4(e0, e1.x, e1.y, e1.z);
        }

        [System.Runtime.CompilerServices.MethodImplAttribute(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        public static vec4u8 vec4(vec3u8 e0, byte e1)
        {
            return DMath.vec4(e0.x, e0.y, e0.z, e1);
        }

        [System.Runtime.CompilerServices.MethodImplAttribute(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        public static vec4u16 vec4(ushort x, ushort y, ushort z, ushort w)
        {
            vec4u16 result = new vec4u16();
            result.x = x;
            result.y = y;
            result.z = z;
            result.w = w;
            return result;
        }

        [System.Runtime.CompilerServices.MethodImplAttribute(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        public static vec4u16 vec4(ushort e)
        {
            return DMath.vec4(e, e, e, e);
        }

        [System.Runtime.CompilerServices.MethodImplAttribute(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        public static vec4u16 vec4(vec2u16 e0, ushort e1, ushort e2)
        {
            return DMath.vec4(e0.x, e0.y, e1, e2);
        }

        [System.Runtime.CompilerServices.MethodImplAttribute(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        public static vec4u16 vec4(ushort e0, vec2u16 e1, ushort e2)
        {
            return DMath.vec4(e0, e1.x, e1.y, e2);
        }

        [System.Runtime.CompilerServices.MethodImplAttribute(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        public static vec4u16 vec4(ushort e0, ushort e1, vec2u16 e2)
        {
            return DMath.vec4(e0, e1, e2.x, e2.y);
        }

        [System.Runtime.CompilerServices.MethodImplAttribute(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        public static vec4u16 vec4(vec2u16 e0, vec2u16 e1)
        {
            return DMath.vec4(e0.x, e0.y, e1.x, e1.y);
        }

        [System.Runtime.CompilerServices.MethodImplAttribute(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        public static vec4u16 vec4(ushort e0, vec3u16 e1)
        {
            return DMath.vec4(e0, e1.x, e1.y, e1.z);
        }

        [System.Runtime.CompilerServices.MethodImplAttribute(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        public static vec4u16 vec4(vec3u16 e0, ushort e1)
        {
            return DMath.vec4(e0.x, e0.y, e0.z, e1);
        }

        [System.Runtime.CompilerServices.MethodImplAttribute(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        public static vec4u32 vec4(uint x, uint y, uint z, uint w)
        {
            vec4u32 result = new vec4u32();
            result.x = x;
            result.y = y;
            result.z = z;
            result.w = w;
            return result;
        }

        [System.Runtime.CompilerServices.MethodImplAttribute(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        public static vec4u32 vec4(uint e)
        {
            return DMath.vec4(e, e, e, e);
        }

        [System.Runtime.CompilerServices.MethodImplAttribute(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        public static vec4u32 vec4(vec2u32 e0, uint e1, uint e2)
        {
            return DMath.vec4(e0.x, e0.y, e1, e2);
        }

        [System.Runtime.CompilerServices.MethodImplAttribute(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        public static vec4u32 vec4(uint e0, vec2u32 e1, uint e2)
        {
            return DMath.vec4(e0, e1.x, e1.y, e2);
        }

        [System.Runtime.CompilerServices.MethodImplAttribute(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        public static vec4u32 vec4(uint e0, uint e1, vec2u32 e2)
        {
            return DMath.vec4(e0, e1, e2.x, e2.y);
        }

        [System.Runtime.CompilerServices.MethodImplAttribute(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        public static vec4u32 vec4(vec2u32 e0, vec2u32 e1)
        {
            return DMath.vec4(e0.x, e0.y, e1.x, e1.y);
        }

        [System.Runtime.CompilerServices.MethodImplAttribute(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        public static vec4u32 vec4(uint e0, vec3u32 e1)
        {
            return DMath.vec4(e0, e1.x, e1.y, e1.z);
        }

        [System.Runtime.CompilerServices.MethodImplAttribute(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        public static vec4u32 vec4(vec3u32 e0, uint e1)
        {
            return DMath.vec4(e0.x, e0.y, e0.z, e1);
        }

        [System.Runtime.CompilerServices.MethodImplAttribute(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        public static vec4u64 vec4(ulong x, ulong y, ulong z, ulong w)
        {
            vec4u64 result = new vec4u64();
            result.x = x;
            result.y = y;
            result.z = z;
            result.w = w;
            return result;
        }

        [System.Runtime.CompilerServices.MethodImplAttribute(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        public static vec4u64 vec4(ulong e)
        {
            return DMath.vec4(e, e, e, e);
        }

        [System.Runtime.CompilerServices.MethodImplAttribute(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        public static vec4u64 vec4(vec2u64 e0, ulong e1, ulong e2)
        {
            return DMath.vec4(e0.x, e0.y, e1, e2);
        }

        [System.Runtime.CompilerServices.MethodImplAttribute(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        public static vec4u64 vec4(ulong e0, vec2u64 e1, ulong e2)
        {
            return DMath.vec4(e0, e1.x, e1.y, e2);
        }

        [System.Runtime.CompilerServices.MethodImplAttribute(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        public static vec4u64 vec4(ulong e0, ulong e1, vec2u64 e2)
        {
            return DMath.vec4(e0, e1, e2.x, e2.y);
        }

        [System.Runtime.CompilerServices.MethodImplAttribute(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        public static vec4u64 vec4(vec2u64 e0, vec2u64 e1)
        {
            return DMath.vec4(e0.x, e0.y, e1.x, e1.y);
        }

        [System.Runtime.CompilerServices.MethodImplAttribute(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        public static vec4u64 vec4(ulong e0, vec3u64 e1)
        {
            return DMath.vec4(e0, e1.x, e1.y, e1.z);
        }

        [System.Runtime.CompilerServices.MethodImplAttribute(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        public static vec4u64 vec4(vec3u64 e0, ulong e1)
        {
            return DMath.vec4(e0.x, e0.y, e0.z, e1);
        }

        [System.Runtime.CompilerServices.MethodImplAttribute(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        public static vec4f16 vec4(System.Half x, System.Half y, System.Half z, System.Half w)
        {
            vec4f16 result = new vec4f16();
            result.x = x;
            result.y = y;
            result.z = z;
            result.w = w;
            return result;
        }

        [System.Runtime.CompilerServices.MethodImplAttribute(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        public static vec4f16 vec4(System.Half e)
        {
            return DMath.vec4(e, e, e, e);
        }

        [System.Runtime.CompilerServices.MethodImplAttribute(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        public static vec4f16 vec4(vec2f16 e0, System.Half e1, System.Half e2)
        {
            return DMath.vec4(e0.x, e0.y, e1, e2);
        }

        [System.Runtime.CompilerServices.MethodImplAttribute(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        public static vec4f16 vec4(System.Half e0, vec2f16 e1, System.Half e2)
        {
            return DMath.vec4(e0, e1.x, e1.y, e2);
        }

        [System.Runtime.CompilerServices.MethodImplAttribute(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        public static vec4f16 vec4(System.Half e0, System.Half e1, vec2f16 e2)
        {
            return DMath.vec4(e0, e1, e2.x, e2.y);
        }

        [System.Runtime.CompilerServices.MethodImplAttribute(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        public static vec4f16 vec4(vec2f16 e0, vec2f16 e1)
        {
            return DMath.vec4(e0.x, e0.y, e1.x, e1.y);
        }

        [System.Runtime.CompilerServices.MethodImplAttribute(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        public static vec4f16 vec4(System.Half e0, vec3f16 e1)
        {
            return DMath.vec4(e0, e1.x, e1.y, e1.z);
        }

        [System.Runtime.CompilerServices.MethodImplAttribute(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        public static vec4f16 vec4(vec3f16 e0, System.Half e1)
        {
            return DMath.vec4(e0.x, e0.y, e0.z, e1);
        }

        [System.Runtime.CompilerServices.MethodImplAttribute(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        public static vec4f32 vec4(float x, float y, float z, float w)
        {
            vec4f32 result = new vec4f32();
            result.x = x;
            result.y = y;
            result.z = z;
            result.w = w;
            return result;
        }

        [System.Runtime.CompilerServices.MethodImplAttribute(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        public static vec4f32 vec4(float e)
        {
            return DMath.vec4(e, e, e, e);
        }

        [System.Runtime.CompilerServices.MethodImplAttribute(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        public static vec4f32 vec4(vec2f32 e0, float e1, float e2)
        {
            return DMath.vec4(e0.x, e0.y, e1, e2);
        }

        [System.Runtime.CompilerServices.MethodImplAttribute(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        public static vec4f32 vec4(float e0, vec2f32 e1, float e2)
        {
            return DMath.vec4(e0, e1.x, e1.y, e2);
        }

        [System.Runtime.CompilerServices.MethodImplAttribute(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        public static vec4f32 vec4(float e0, float e1, vec2f32 e2)
        {
            return DMath.vec4(e0, e1, e2.x, e2.y);
        }

        [System.Runtime.CompilerServices.MethodImplAttribute(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        public static vec4f32 vec4(vec2f32 e0, vec2f32 e1)
        {
            return DMath.vec4(e0.x, e0.y, e1.x, e1.y);
        }

        [System.Runtime.CompilerServices.MethodImplAttribute(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        public static vec4f32 vec4(float e0, vec3f32 e1)
        {
            return DMath.vec4(e0, e1.x, e1.y, e1.z);
        }

        [System.Runtime.CompilerServices.MethodImplAttribute(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        public static vec4f32 vec4(vec3f32 e0, float e1)
        {
            return DMath.vec4(e0.x, e0.y, e0.z, e1);
        }

        [System.Runtime.CompilerServices.MethodImplAttribute(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        public static vec4f64 vec4(double x, double y, double z, double w)
        {
            vec4f64 result = new vec4f64();
            result.x = x;
            result.y = y;
            result.z = z;
            result.w = w;
            return result;
        }

        [System.Runtime.CompilerServices.MethodImplAttribute(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        public static vec4f64 vec4(double e)
        {
            return DMath.vec4(e, e, e, e);
        }

        [System.Runtime.CompilerServices.MethodImplAttribute(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        public static vec4f64 vec4(vec2f64 e0, double e1, double e2)
        {
            return DMath.vec4(e0.x, e0.y, e1, e2);
        }

        [System.Runtime.CompilerServices.MethodImplAttribute(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        public static vec4f64 vec4(double e0, vec2f64 e1, double e2)
        {
            return DMath.vec4(e0, e1.x, e1.y, e2);
        }

        [System.Runtime.CompilerServices.MethodImplAttribute(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        public static vec4f64 vec4(double e0, double e1, vec2f64 e2)
        {
            return DMath.vec4(e0, e1, e2.x, e2.y);
        }

        [System.Runtime.CompilerServices.MethodImplAttribute(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        public static vec4f64 vec4(vec2f64 e0, vec2f64 e1)
        {
            return DMath.vec4(e0.x, e0.y, e1.x, e1.y);
        }

        [System.Runtime.CompilerServices.MethodImplAttribute(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        public static vec4f64 vec4(double e0, vec3f64 e1)
        {
            return DMath.vec4(e0, e1.x, e1.y, e1.z);
        }

        [System.Runtime.CompilerServices.MethodImplAttribute(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        public static vec4f64 vec4(vec3f64 e0, double e1)
        {
            return DMath.vec4(e0.x, e0.y, e0.z, e1);
        }
    }
}

