<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Silk.NET"  />
		<PackageReference Include="Silk.NET.Core"  />
		<PackageReference Include="Silk.NET.SDL"  />
		<PackageReference Include="Silk.NET.Windowing"  />
		<PackageReference Include="Silk.NET.Input"  />
		<PackageReference Include="Silk.NET.Vulkan" />
		<PackageReference Include="Silk.NET.Vulkan.Extensions.EXT" />
		<PackageReference Include="Silk.NET.Shaderc" />
		<PackageReference Include="Silk.NET.Shaderc.Native" />
		<PackageReference Include="DotNext.Unsafe" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="CommunityToolkit.HighPerformance" />
		<PackageReference Include="Alimer.Bindings.WebGPU" />
		<PackageReference Include="Alimer.WebGPU.Native" />
		<PackageReference Include="SixLabors.ImageSharp" />
		<PackageReference Include="System.Reactive" />
		<PackageReference Include="Varena" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\DualDrill.Common\DualDrill.Common.csproj" />
	</ItemGroup>
</Project>