<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <RuntimeIdentifier>linux-x64</RuntimeIdentifier>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DualDrill.APIDefinition\DualDrill.ApiGen.csproj" />
    <ProjectReference Include="..\DualDrill.Graphics\DualDrill.Graphics.csproj" />
    <ProjectReference Include="..\DualDrill.ILSL\DualDrill.ILSL.csproj" />
    <ProjectReference Include="..\DualDrill.Shaders\DualDrill.Shaders.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="..\DualDrill.CLSL.Test\ShaderModule\MinimumHelloTriangleShaderModule.cs"
             Link="ShaderModule\MinimumHelloTriangleShaderModule.cs" />
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Reference\reference-Xds3zN.glslf"
          CopyToOutputDirectory="PreserveNewest"
          CopyToPublishDirectory="PreserveNewest" />
    <AssemblyMetadata Include="RaymarchReferenceCommit"
                      Value="5db58051fa019b591e4e13a53b1dceef8e37ea4f" />
    <AssemblyMetadata Include="RaymarchReferenceSha256"
                      Value="59e27ceb51248f33c7228ca458f443c6fcd1fb16c09a5975ad277f1adfe8bdda" />
  </ItemGroup>

</Project>
